version: '3.7'

services:
  camunda-nginx:
    image: nginx:1.19.6
    restart: always
    container_name: camunda-cockroach-gateway-$ENVIRONMENT
    hostname: 'camunda-gateway'
    depends_on:
      - camunda-engine1
    ports:
      - "$CLUSTER_GATE_PORT:443"
    expose:
      - 443
    volumes:
      - ./cfg/camunda-${ENVIRONMENT}.conf:/etc/nginx/conf.d/default.conf:ro
      - ./cfg/ssl/camunda.crt:/ssl/camunda.crt:ro
      - ./cfg/ssl/camunda.key:/ssl/camunda.key:ro
      - ./cfg/ssl/dhparam.pem:/ssl/dhparam.pem:ro
      #- ./cfg/logrotate.nginx:/etc/logrotate.d/nginx:ro
      #- ./logs/:/var/log/nginx/
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:
        aliases:
          - camunda-gateway        
    extra_hosts:
      - "camunda:$CAMUNDA"
      - "camunda2:$CAMUNDA2"

  camunda-engine1:
    image: camunda-plugins
    container_name: camunda-cockroach-engine1-$ENVIRONMENT
    hostname: 'camunda-engine1'
    restart: always
    depends_on:
      - db
    networks:
      default:
    expose:
      - 8080
      - 8443
    volumes:
      - ./cfg/server.xml:/camunda/conf/server.xml:ro
      - ./cfg/ssl/camunda.p12:/camunda/conf/camunda.p12:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SERVER
      - CAMUNDA_PASSWORD
      - RedisUrls=$REDIS_PORTS
      - RedisPass=$REDIS_PASSWORD
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://${DB_PORT}/defaultdb?sslmode=disable
      - DB_USER=root
      - DB_PASSWORD=
      - DB_CONN_MAXACTIVE=100
      - WAIT_FOR=${DB_PORT}
      - WAIT_FOR_TIMEOUT=60
      - TZ=Europe/Kiev
      - JMX_PROMETHEUS=false
    extra_hosts:
      - "camunda:$CAMUNDA"
      - "camunda2:$CAMUNDA2"

  camunda-engine2:
    image: camunda-plugins
    container_name: camunda-cockroach-engine2-$ENVIRONMENT
    hostname: 'camunda-engine2'
    restart: always
    depends_on:
      - db
    networks:
      default:
    expose:
      - 8080
      - 8443
    volumes:
      - ./cfg/server.xml:/camunda/conf/server.xml:ro
      - ./cfg/ssl/camunda.p12:/camunda/conf/camunda.p12:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SERVER
      - CAMUNDA_PASSWORD
      - RedisUrls=$REDIS_PORTS
      - RedisPass=$REDIS_PASSWORD
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://${DB_PORT}/defaultdb?sslmode=disable
      - DB_USER=root
      - DB_PASSWORD=
      - DB_CONN_MAXACTIVE=100
      - WAIT_FOR=${DB_PORT}
      - WAIT_FOR_TIMEOUT=60
      - TZ=Europe/Kiev
      - JMX_PROMETHEUS=false
    extra_hosts:
      - "camunda:$CAMUNDA"
      - "camunda2:$CAMUNDA2"

  worker1:
    image: camunda-plugins-worker
    container_name: camunda-cockroach-worker1-$ENVIRONMENT
    restart: always
    depends_on:
      - camunda-engine1
      - redis1
    networks:
      default:
    environment:
      - ENVIRONMENT
      - SERVER
      - LogLevel=info
      - CamundaUrl=http://camunda-engine1:8080/engine-rest
      - RedisUrls=$REDIS_PORTS
      - workerId=worker1
      - CamundaPass=$CAMUNDA_PASSWORD
      - RedisPass=$REDIS_PASSWORD
      - JobsToActivate=200
      - LongPolling=60000
      - TaskType=InternalService
      # rotate logfile days
      - maxLogDays=14
      # rotate error logfile days
      - maxLogErrDays=60
      # keep redis file cache in Hours
      - redisCacheHours=1
    volumes:
      - ./logs:/logs
      - ./workers/node/server.js:/app/server.js:ro
      - ./workers/js:/app/js
      # - ./cfg/ssl/rootcamundaCA.crt:/ssl/camundaCA.crt:ro
      - /etc/localtime:/etc/localtime:ro
    extra_hosts:
      - "camunda:$CAMUNDA"
      - "camunda2:$CAMUNDA2"

  worker2:
    image: camunda-plugins-worker
    container_name: camunda-cockroach-worker2-$ENVIRONMENT
    restart: always
    depends_on:
      - camunda-engine2
      - redis1
    networks:
      default:
    environment:
      - ENVIRONMENT
      - SERVER
      - LogLevel=info
      - CamundaUrl=http://camunda-engine2:8080/engine-rest
      - RedisUrls=$REDIS_PORTS
      - workerId=worker2
      - CamundaPass=$CAMUNDA_PASSWORD
      - RedisPass=$REDIS_PASSWORD
      - JobsToActivate=200
      - LongPolling=60000
      - TaskType=InternalService
      # rotate logfile days
      - maxLogDays=14
      # rotate error logfile days
      - maxLogErrDays=60
      # keep redis file cache in Hours
      - redisCacheHours=1
    volumes:
      - ./logs:/logs
      - ./workers/node/server.js:/app/server.js:ro
      - ./workers/js:/app/js
      # - ./cfg/ssl/rootcamundaCA.crt:/ssl/camundaCA.crt:ro
      - /etc/localtime:/etc/localtime:ro
    extra_hosts:
      - "camunda:$CAMUNDA"
      - "camunda2:$CAMUNDA2"

  db:
    image: cockroachdb/cockroach:v20.2.5
    restart: always
    container_name: camunda-cockroach-db1-$ENVIRONMENT
    hostname: node1
    command: start --insecure --join node1,node2,node3
    ports:
      - "$DB_PORT:26257"
      - "$HTTP_PORT:8080"
    networks:
      default:
        aliases:
          - node1
    volumes:
      - ./db/roach1:/cockroach/cockroach-data
      - /etc/localtime:/etc/localtime:ro

  db2:
    image: cockroachdb/cockroach:v20.2.5
    restart: always
    container_name: camunda-cockroach-db2-$ENVIRONMENT
    hostname: node2
    command: start --insecure --join node1,node2,node3
    networks:
      default:
        aliases:
          - node2
    volumes:
      - ./db/roach2:/cockroach/cockroach-data
      - /etc/localtime:/etc/localtime:ro

  db3:
    image: cockroachdb/cockroach:v20.2.5
    restart: always
    container_name: camunda-cockroach-db3-$ENVIRONMENT
    hostname: node3
    command: start --insecure --join node1,node2,node3
    networks:
      default:
        aliases:
          - node3
    volumes:
      - ./db/roach3:/cockroach/cockroach-data
      - /etc/localtime:/etc/localtime:ro

  # odd number of redis for redlock quorum (1 or 3 or more)
  redis1:
    image: redis:6.0.7
    container_name: camunda-cockroach-redis1-$ENVIRONMENT
    restart: always
    ports:
      - "$REDIS_PORT1:6379"
    expose:
      - 6379
    networks:
      default:
    volumes:
      - ./redis/1:/data
      - ./cfg/redis.conf:/redis.conf:ro
      - /etc/localtime:/etc/localtime:ro
    command: [ "redis-server", "/redis.conf" ]

  redis2:
    image: redis:6.0.7
    container_name: camunda-cockroach-redis2-$ENVIRONMENT
    restart: always
    ports:
      - "$REDIS_PORT2:6379"
    expose:
      - 6379
    networks:
      default:
    volumes:
      - ./redis/2:/data
      - ./cfg/redis.conf:/redis.conf:ro
      - /etc/localtime:/etc/localtime:ro
    command: [ "redis-server", "/redis.conf" ]

  redis3:
    image: redis:6.0.7
    container_name: camunda-cockroach-redis3-$ENVIRONMENT
    restart: always
    ports:
      - "$REDIS_PORT3:6379"
    expose:
      - 6379
    networks:
      default:
    volumes:
      - ./redis/3:/data
      - ./cfg/redis.conf:/redis.conf:ro
      - /etc/localtime:/etc/localtime:ro
    command: [ "redis-server", "/redis.conf" ]

networks:
  default:
    name: camunda-cockroach-$ENVIRONMENT
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: $CLUSTER_NETWORK
